# Generated by Django 4.0.4 on 2022-05-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wapp',
            new_name='student',
        ),
    ]
