# Generated by Django 4.0.4 on 2022-05-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0003_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wapp.student'),
        ),
    ]
