# Generated by Django 4.0.4 on 2022-05-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0004_subjects_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='subject',
            new_name='subjects',
        ),
    ]
